server:
  port: 8081
  
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://192.168.80.230:3306/dev
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.80.230:8761/eureka/
