server:
  port: 8099
  
spring:
  application:
    name: user-service
 
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/  

zuul:
  routes:
    user-webservice: /user/**
      
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.80.230:8761/eureka/
