server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  data:
    mongodb:
      uri: mongodb://192.168.80.230
 
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/  

zuul:
  routes:
    load-balance: /api/user/**
    account-lb: /api/account/**
    auth-lb: /api/device/**
    strongauth-lb: /api/strongauth/**
    sentemail-lb: /api/email/**

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: false    
---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.80.230:8761/eureka/
